Repository Beomman-Han/biotools, pull requests merged in 2022-03, with the labels that each got.

#5 fix sanity check and add find_seq
  FASTA/FASTA.py
Labels: enhancement

#6 add find_title method
  FASTA/FASTA.py
Labels: enhancement

#9 Update 'varRecord' class
  FASTA/BAM.py
  VCF/VCF.py
  VCF/varRecord.py
Labels: documentation, enhancement

#10 Refine existing methods at VCF/VCF.py
  FASTA/BAM.py
  File.py
  VCF/VCF.py
  VCF/varRecord.py
Labels: documentation

#12 Update README.md
  README.md
Labels: documentation
